name       : python-py-cpuinfo
version    : 8.0.0
release    : 4
source     :
    - https://github.com/workhorsy/py-cpuinfo/archive/v8.0.0.tar.gz : a8cecd8ec33c67854c5df2a5c0fc72c7baebef2796028e28c3de139734f5c170
homepage   : https://github.com/workhorsy/py-cpuinfo
license    : MIT
component  : programming.python
summary    : A module for getting CPU info with Python
description: |
    Py-cpuinfo gets CPU info with pure Python. Py-cpuinfo should work without any extra programs or libraries, beyond what your OS provides. It does not require any compilation(C/C++, assembly, et cetera) to use.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
