name       : python-py-cpuinfo
version    : 7.0.0
release    : 2
source     :
    - https://github.com/workhorsy/py-cpuinfo/archive/v7.0.0.tar.gz : 2f6d6e2a25b6a643f19de0b8f032c1b64e36ae3a461843b2c1aafbcdd97dc2e1
homepage   : https://github.com/workhorsy/py-cpuinfo
license    : MIT
component  : programming.python
summary    : A module for getting CPU info with Python
description: |
    Py-cpuinfo gets CPU info with pure Python. Py-cpuinfo should work without any extra programs or libraries, beyond what your OS provides. It does not require any compilation(C/C++, assembly, et cetera) to use.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
